DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS film_genre CASCADE;
DROP TABLE IF EXISTS friendship CASCADE;
DROP TABLE IF EXISTS film CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS mpa_rating CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(100) NOT NULL UNIQUE,
    login    VARCHAR(100) NOT NULL UNIQUE,
    name     VARCHAR(100) NOT NULL,
    birthday DATE         NOT NULL
    );

CREATE TABLE IF NOT EXISTS mpa_rating
(
    mpa_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(200) NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS genre
(
    genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS film
(
    film_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    description  TEXT         NOT NULL,
    release_date DATE         NOT NULL CHECK (release_date >= '1895-12-28'),
    duration     INTEGER      NOT NULL CHECK (duration > 0),
    mpa_id       BIGINT REFERENCES mpa_rating (mpa_id) ON DELETE RESTRICT
    );

CREATE TABLE IF NOT EXISTS friendship
(
    user_id      BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    friend_id    BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    is_confirmed BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (user_id, friend_id),
    CHECK (user_id != friend_id)
    );

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  BIGINT NOT NULL REFERENCES film (film_id) ON DELETE CASCADE,
    genre_id BIGINT NOT NULL REFERENCES genre (genre_id) ON DELETE RESTRICT,
    PRIMARY KEY (film_id, genre_id)
    );

CREATE TABLE IF NOT EXISTS likes
(
    film_id BIGINT NOT NULL REFERENCES film (film_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
    );


INSERT INTO mpa_rating (mpa_id, name, description) VALUES (1, 'G', 'Нет возрастных ограничений');
INSERT INTO mpa_rating (mpa_id, name, description) VALUES (2, 'PG', 'Рекомендуется присутствие родителей');
INSERT INTO mpa_rating (mpa_id, name, description) VALUES (3, 'PG-13', 'Детям до 13 лет просмотр не желателен');
INSERT INTO mpa_rating (mpa_id, name, description) VALUES (4, 'R', 'Лицам до 17 лет обязательно присутствие взрослого');
INSERT INTO mpa_rating (mpa_id, name, description) VALUES (5, 'NC-17', 'Лицам до 18 лет просмотр запрещен');


INSERT INTO genre (genre_id, name) VALUES (1, 'Комедия');
INSERT INTO genre (genre_id, name) VALUES (2, 'Драма');
INSERT INTO genre (genre_id, name) VALUES (3, 'Мультфильм');
INSERT INTO genre (genre_id, name) VALUES (4, 'Триллер');
INSERT INTO genre (genre_id, name) VALUES (5, 'Документальный');
INSERT INTO genre (genre_id, name) VALUES (6, 'Боевик');